### ISSUE TITLE
Can't built on Linux(Raspberry Pi)

### ISSUE THREAD

**Issue by tkelestemur** [aldebaran/liburg#1]
Hi, I am unable to build this library on Raspberry Pi. I get this error:

```
zsh: no such file or directory: ./configure
```

I also tried on MacOS.

**Comment by tSed** [comment]
Hi,

Since it's sources from vcs repository, you have to autoreconf the project in order to generate the configure script.

See [1] for more details about autotools-based projects.

[1] http://en.wikipedia.org/wiki/GNU_build_system

Regards,

**Comment by tkelestemur** [comment]
I installed autoconf tool and run it inside of the liburg folder and get this log 

```
pi@raspberrypi ~/Desktop/liburg $ sudo autoconf
configure.in:7: error: possibly undefined macro: AM_INIT_AUTOMAKE
  If this token and others are legitimate, please use m4_pattern_allow.
  See the Autoconf documentation.
configure.in:9: error: possibly undefined macro: AM_CONFIG_HEADER
configure.in:24: error: possibly undefined macro: AC_PROG_LIBTOOL
configure.in:50: error: possibly undefined macro: AM_CONDITIONAL
```

I checked but couldn't find any solution.

btw: thanks for fast reply.

**Comment by tSed** [comment]
@tkelestemur said:

> pi@raspberrypi ~/Desktop/liburg $ sudo autoconf

Gahhhh! you don't need root privileges to build a package, just need them when you install it in the system (i.e. / or somewhere else you, as user, don't have write permissions).

Anyway, to autoconf/autoreconf the project, you should try: `autoreconf -isfv`

**Comment by tkelestemur** [comment]
I've just tried but couldn't do it. Log can be found below. 
I also tried autoreconf -i. 

```
pi@raspberrypi ~/Desktop/liburg $ autoreconf -isfv
autoreconf: Entering directory `.'
autoreconf: configure.in: not using Gettext
autoreconf: running: aclocal --force
autom4te: cannot open autom4te.cache/requests: Permission denied
aclocal: /usr/bin/autom4te failed with exit status: 1
autoreconf: aclocal failed with exit status: 1
pi@raspberrypi ~/Desktop/liburg $ ./configure
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."
pi@raspberrypi ~/Desktop/liburg $
```

**Comment by tSed** [comment]
> pi@raspberrypi ~/Desktop/liburg $ autoreconf -isfv
> autoreconf: Entering directory `.'
> autoreconf: configure.in: not using Gettext
> autoreconf: running: aclocal --force
> autom4te: cannot open autom4te.cache/requests: Permission denied

This smells like the tree is not clean (certainly some remaining stuff from the `sudo autoconf` command...

If you are using a git view, try `git clean -fdx`, then manually remove all files on which git fails because of  missing permissions, and finally run again `autoreconf -isfv`

**Comment by tkelestemur** [comment]
Yess, problem is solved. I could manage to run `autoreconf ./configure and make` without any problem. Thank you very much.

However when I go samples I see only c folder  was compiled. When I try to go inside cpp folder and try `make` command I get error. I think when it reconfigure library it arranged something wrong.
Here is the error:

```
pi@raspberrypi ~/Desktop/urg-libs/liburg/samples/cpp $ make
/bin/bash ../../libtool --tag=CXX   --mode=link g++  -g -O2    -o versionLines versionLines.o  -L../../src/c/urg -L../../src/c/connection -L../../src/c/system -L../../src/cpp/urg -L../../src/cpp/connection -L../../src/cpp/common -L../../src/cpp/system -L../../src/cpp/monitor -L../../src/cpp/coordinate -L../../src/cpp/geometry -L../../src/cpp/connection/sdl -lurg_monitor -lurg -lurg_coordinate -lurg_geometry -lurg_connection -lurg_connection_sdl -lurg_common -lurg_system -lm
libtool: link: g++ -g -O2 -o versionLines versionLines.o  -L../../src/c/urg -L../../src/c/connection -L../../src/c/system -L../../src/cpp/urg -L../../src/cpp/connection -L../../src/cpp/common -L../../src/cpp/system -L../../src/cpp/monitor -L../../src/cpp/coordinate -L../../src/cpp/geometry -L../../src/cpp/connection/sdl -lurg_monitor -lurg -lurg_coordinate -lurg_geometry -lurg_connection -lurg_connection_sdl -lurg_common -lurg_system -lm
/usr/bin/ld: cannot find -lurg_monitor
/usr/bin/ld: cannot find -lurg
/usr/bin/ld: cannot find -lurg_coordinate
/usr/bin/ld: cannot find -lurg_geometry
/usr/bin/ld: cannot find -lurg_connection
/usr/bin/ld: cannot find -lurg_connection_sdl
/usr/bin/ld: cannot find -lurg_common
/usr/bin/ld: cannot find -lurg_system
collect2: ld returned 1 exit status
Makefile:349: recipe for target 'versionLines' failed
make: *** [versionLines] Error 1
```
